### ISSUE TITLE
1장. 웹과 네트워크의 기본에 대해 알아보자

### ISSUE THREAD

**Issue by hhhyunwoo** [WhiteKow/http-network-basic-study#1]

**Comment by hhhyunwoo** [comment]
# 1장. 웹과 네트워크의 기본에 대해 알아보자

# HTTP

- HypterText Transfer Protocol
- 말그대로 프로토콜! 규약을 의미함
- 즉, 웹은 HTTP 라는 프로토콜을 사용한 통신으로 이루어져 있음

# HTTP1.1 vs HTTP2.0

## HTTP1.1

- HTTP/1.1 은 기본적으로 Connection 당 하나의 요청을 처리하도록 설계
- 동시 전송이 불가능하고 요청과 응답이 순차적으로 이루어짐.
- HTTP 문서 안에 포함된 다수의 리소스를 처리하려면 요청할 리소스 개수에 비례해서 Latency (대기 시간)이 길어짐.

### **단점**

- 무거운 Header 구조 (특히 Cookie)
- HOL (Head Of Line) Blocking - 특정 응답의 지연
    -  ![image](https://user-images.githubusercontent.com/37402136/194586621-d71aa49c-ab38-40d9-8c8f-057042ed6388.png)
    

## HTTP2.0

- 성능에 초점
- 최종 사용자가 대기 시간, 네트워크 및 서버 리소스 사용을 인식
- 하나는 브라우저에서 웹 사이트로의 단일 연결을 허용하는 것
- 한 커넥션으로 동시에 여러 개의 메시지를 주고 받을 수 있으며, 응답은 순서에 상관없이 stream으로 주고 받음.
- server push
    - 클라이언트가 요청하지 않은 리소스를 push 해주는 방법

# TCP/IP

- 일반적으로 사용하고 있는 네트워크는 TCP/IP 라는 프로토콜에서 움직임
- HTTP도 TCP/IP 중 하나임
- 프로토콜의 집합!

![image](https://user-images.githubusercontent.com/37402136/194586652-724f7b48-5fd1-4440-8f27-a6b130e799f7.png)


## Application

- 유저에게 제공되는 애플리케이션에서 사용하는 통신의 움직임을 결정함
- HTTP, FTP, DNS 등도 이 중 한가지

### DNS (Domain Name System)

- 도메인 이름을 통해서 IP주소를 찾을 수 있음

## Transport

- 애플리케이션 계층에 네트워크로 접속되어 있는 2대의 컴퓨터 사이의 흐름을 제공

### TCP (Transfer Control Protocol)

- 신뢰성 있는 바이트 스트림 서비스를 제공함
- 용량이 큰 데이터를 보내기 쉽게 TCP 세그먼트라고 불리는 단위 패킷으로 작게 분해하여 관리
- 3 Way Handshaking
    - SYN → SYN/ACK → ACK

### UDP (User Datagram Protocol)

- 비연결형 서비스로 데이터그램 방식을 제공한다

## Internet

- 네트워크 상에서 패킷의 이동을 다룸
- 패킷
    - 전송하는 데이터의 최소 단위

### **IP (**Internet Protocol)

- 변경 가능
- 각 노드에 부여된 주소를 가리킴
- ARP (Address Resolution Protocol) 을 사용해서 MAC을 찾아감
    - 주소를 해결하기 위한 프로토콜 중 하나. 수신지의 IP 주소를 바탕으로 MAC을 알 수 있음.

### MAC (Media Access Control Address)

- 변경 안됨
- 네트워크 카드에 할당된 고유의 주소

## Network(Link)

- 네트워크에 접속하는 하드웨어적인 면을 다룸

# 주소 입력란에 URL을 입력했을 때의 과정

# URL, URI

- URL 은 URI(식별자) 의 서브셋

**Comment by jjangsungwon** [comment]
## 1장. 웹과 네트워크의 기본에 대해 알아보자
웹이라는 세계가 어떤 기술로 구성되어 있는지. HTTP 는 어떤 역사를 가지고 있는지 알게되었다. 이러한 배경을 이해하는 것은 HTTP 에 대한 깊은 이해를 도와준다. 

<br>

### 웹은 HTTP 로 나타낸다
- 웹 브라우저는 웹 브라우저 주소 입력란에 지정된 URL 에 의지해서 웹 서버로부터 리소스라고 불리는 파일 등의 정보를 얻는다.
- 클라이언트에서 서버까지 일련의 흐름을 결정하고 있는 것은 웹에서 HTTP 라고 불리는 프로토콜이다.
- 프로토콜은 약속을 의미한다. 즉, 웹은 HTTP 라는 약속을 사용한 통신으로 이루어져 있다.

### HTTP  역사
- 웹은 지식 공유를 위해 고안되었다.
- 1990년 CERN 에서 세계 최초의 웹 서버와 웹 브라우저가 개발되었다.
- 1993년 대한민국 최초의 홈페이지가 개발되었다.
- 1993년 1월 NCSA(미국 수퍼 컴퓨터 응용 연구소)에서 웹 브라우저의 선조라고 말할 수 있는 모자이크가 개발되었다.
- 1996년 5월 HTTP가 정식 사양으로 공개되었다. 그리고 이 무렵에 본격적으로 브라우저 경쟁이 과열되는 시기가 시작되었다.

### TCP/IP
- 인터넷을 포함하여 일반적으로 사용하고 있는 네트워크는 TCP/IP라는 프로토콜에서 움직이고 있다. HTTP 도 그 중 하나이다. (IP 프로토콜을 사용한 통신에서 사용되고 있는 프로토콜을 총칭해서 TCP/IP라는 이름이 사용되기도 한다.)
- 컴퓨터가 통신하기 위해서는 서로 같은 방법으롤 해야 한다.
- 계층 구조이다. (애플리케이션, 트랜스포트, 네트워크, 링크)
  - 계층 구조는 설계를 편하게 할 수 있고 변경된 해당 계층만 바꾸면 되는 메리트가 있다.
  - 애플리케이션: 유저에게 제공되는 통신의 움직임 결정 (ex, FTP, DNS, HTTP)
  - 트랜스포트: 데이터 흐름 제공
  - 네트워크: 패킷의 이동을 다룸 (패킷: 전송하는 데이터의 최소 단위)
  - 링크: 네트워크에 접속하는 하드웨어적인 면을 다룸

### IP (Internet Protocol)
- 네트워크 계층
- IP 주소와 다른 말. IP는 프로토콜의 명칭
- 패킷을 상대방에세 전달하는 역할을 수행함.
- IP 주소는 각 노드에 부여된 주소를 가리킴 (MAC 주소는 네트워크 카드에 할당된 고유의 주소)
- IP 주소는 MAC 주소와 결부됨. IP 주소는 변경 가능하지만 기본적으로 MAC 주소는 변경할 수 없음
- ARP 프로토콜을 활용하여 MAC 주소를 찾음
- 네트워크 기기는 목적지에 도착하기까지 대략적인 목적지만을 알고 있음 (A -> B -> C ... A는 B까지만 알고 B는 C까지만 알고) - 라우팅 개념

### TCP (Transfer Control Protocol)
- 트랜스포트 계층
- 신뢰성 있는 바이트 스트림 서비스 제공
  - 바이트 스트림: 용량이 큰 데이터를 보내기 쉽게 TCP 세그먼트라고 불리는 단위 패킷으로 작게 분해하여 관리하는 것
- 대용량의 데이터를 보내기 쉽게 작게 분해하여 상대에게 보내고, 정확하게 도착했는지 확인하는 역할을 담당하고 있음
- 3-way-handshaking 방법을 통해 상대방에게 확실하게 데이터를 보냈는지 확인함


### DNS (Domain Name System)
- 응용 계층 시스템에서 도메인 이름과 IP 주소 이름 확인을 제공함
- 사람은 숫자를 나열하는 IP 주소를 지정하는 것보다 영어나 숫자 등으로 표기해 컴퓨터의 이름을 지정하는 것이 편리함. 하지만, 컴퓨터는 반대. 이를 해결하기 위해서 DNS 가 존재함.
- DNS는 도메인명에서 IP 주소를 조사하거나 반대로 IP 주소로부터 도메인명을 조사하는 서비스를 제공하고 있음


### URI, URL (Uniform Resource Identifier, Locator)
- Uniform: 통합된 서식을 결정
- Resource: 식별 가능한 모든 것
- Identifier: 식별 가능한 것을 참조하는 오브젝트
- URI는 리소스를 식별하기 위해 문자열 전반을 나타낸다.
- URL은 리소스의 장소를 나타낸다.

**Comment by ChanhuiSeok** [comment]
### 네트워크의 기본은 TCP/IP
- HTTP는 TCP/IP라는 프로토콜 중 하나이다.
- TCP/IP에서 중요한 개념은 **계층**이다. (애플리케이션, 트랜스포트, 네트워크, 링크 계층으로 4게층으로 나뉨)
    - 계층화되어 있어서 사양이 변경된 해당 계층만 바꾸면 됨
    - 애플리케이션 계층 - 유저에게 제공되는 애플리케이션에서 사용하는 통신의 움직임 결정 (FTP, DNS, HTTP,..)
    - 트랜스포트 계층 - 애플리케이션 계층에 네트워크로 접속되어 있는 2대의 컴퓨터 사이의 데이터 흐름 (TCP, UDP)
    - 네트워크 계층 - 네트워크 상에서 패킷의 이동을 다룸 (IP)
    - 링크 계층 - 네트워크에 접속하는 하드웨어적인 면을 다룸
- TCP/IP는 통신을 할 때 송신측은 애플리케이션 계층(예: HTTP 리퀘스트)에서부터 내려가고, 수신하는 측은 애플리케이션 계층으로 올라가는 흐름을 가진다. 각 계층을 거칠 때 송신측은 헤더가 추가되고, 수신측은 계층을 거쳐갈 때마다 해당 계층마다 사용한 헤더를 삭제한다.

### IP/TCP/DNS
- IP : 네트워크 층에 해당. 개개의 패킷을 상대방에게 전달하는 것. IP 주소는 각 노드에 부여된 주소를 가리키고, MAC 주소는 각 네트워크 카드에 할당된 고유의 주소이다. IP 주소는 변경 가능, 기본적으로 MAC 주소는 변경 불가
    - IP 통신은 MAC 주소에 의존해서 통신한다. 인터넷에서 여러 대 컴퓨터, 네트워크 기기를 중계하여 상대방에게 도착하는데 중계 동안에 다음으로 중계할 곳의 MAC 주소를 사용해 목적지를 찾아간다. 이 때 ARP라는 프로토콜이 사용된다.
    - **ARP** : 주소를 해결하기 위한 프로토콜 중 하나. 수신지의 IP 주소를 바탕으로 MAC 주소 조사
- TCP : 신뢰성을 담당. 트랜스포트 계층에 해당한다. TCP는 대용량 데이터를 보내기 쉽게 작게 분해해 상대방에게 보내고, 정확하게 도착했는지 확인하는 역할을 담당한다. (3 way handshaking - 보내졌는지 여부를 상대에게 확인)
- DNS : 이름 해결을 담당. 도메인명에서 IP 주소를 조사, 혹은 IP 주소로부터 도메인명을 조사.
