### ISSUE TITLE
10장. 웹 콘텐츠에서 사용하는 기술

### ISSUE THREAD

**Issue by jjangsungwon** [WhiteKow/http-network-basic-study#10]

**Comment by jjangsungwon** [comment]
### 웹 콘텐츠 사용 기술
- 초기 웹이 등장한 무렵에는 심플한 콘텐츠만 존재하였다.
- 현재 웹의 세계에는 다양한 콘텐츠를 송신할 필요가 있고 이를 위해서 여러 가지 기술이 사용되고 있다.

### 1. HTML
- HTML (HyperText Markup Language)은 웹 상에서 하이퍼텍스트를 보내기 위해서 개발된 언어이다.
- 하이퍼텍스트는 문서 중에 임의의 장소의 정보가 다른 정보에 관련된 즉 링크되어 있는 문서를 말한다.
- 마크업 언어: 문서의 일부에 특별한 문자열을 붙임으로써, 문서를 수식하는 언어
#### 1.1 HTML 버전
- HTML1.0: 1993, 모자이크가 해석할 수 있는 HTML의 사양 (모자이크: NSCA에서 발표한 브라우저)
- HTML5: 텍스트를 데이터로 다룰 수 있도록 함. 애니메이션 등의 효과 제공 
#### 1.2 CSS
- CSS (Cascading Style Sheets)는 HTML 각 요소를 어떻게 표시할지 지시하는 것으로, 스타일 시트라고 불리는 사양 중의 하나이다.
- 문서의 구조와 디자인을 분리한다는 이념에서 만들어짐.

### 2. 다이나믹 HTML
#### 2.1 DOM
- DOM (Document Object Model)은 HTML 문서와 XML문서를 위한 API
- HTML내의 요소를 오브젝트로 다룰 수 있음 -> 요소 낸의 문자열 추출, CSS를 프로퍼티로서 변경해 디자인 변경 가능
- JavaScript 등의 스크립트를 사용하여 HTML 쉽게 조작 가능

### 3. 웹 애플리케이션
- 웹 애플리케이션은 웹 기능을 사용해서 제공되는 프로그램을 말한다.
- 초기 HTTP를 사용한 웹 구조는 사전에 준비된 콘텐츠만 활용하였다. 그러나 웹이 보급됨에 따라 이것만으로는 부족해서 프로그램이 HTML 등의 콘텐츠를 생성할 필요가 생기게 되었다. (동적 콘텐츠)

#### 3.1 CGI
- CGI (Common Gateway Interface)는 웹 서버가 클라이언트에서 받은 리퀘스트를 프로그램에 전달하기 위한 구조이다.
- CGI에 의해 프로그램은 리퀘스트 내용에 맞게 HTML을 생성하는 등으로 동적으로 콘텐츠 생성 가능 (ex, PHP, Ruby, C)

#### 3.2 서블릿
- 서블릿 (Servlet)은 서버 상에 HTML 등의 동적 콘텐츠를 생성하기 위한 프로그램을 가리킨다.
- JavaEE (Java Enterprise Edition)의 일부로서 제공되고 있다.
- CGI는 리퀘스트마다 프로그램을 가동하기 때문에 대량의 액세스가 있을 때 웹 서버에 부하가 걸리게 되지만 서블릿은 웹 서버와 같은 프로세스 속에서 동작하기 때문에 비교적 부하를 적게 하여 동작시킬 수 있다.

### 4. 데이터 송신 포맷, 언어
#### 4.1 XML
- XML (eXtensible Markup Language)는 목적에 맞게 확장 가능한 마크업 언어이다.
- HTML과 같은 문서 기술 언어에서 파생된 것이지만 HTML에 비해서 데이터를 기술하는 것에 특화되어 있다.
- XML 구조는 태그로 나뉘어져 있고 트리 구조로 되어 있기 때문에 구조를 해석하고 요소를 뽑아내는 파서 기능에 의해서 데이터 추출을 쉽게 할 수 있다.
- 데이터를 재사용하기 쉽다는 점에서 XML은 인터넷에서 널리 이용되고 있다.

#### 4.2 RSS/Atom
- 뉴스나 블로그의 기사 등의 갱신 정보를 송신하기 위한 문서 포맷의 총칭으로 RSS, Atom 모두 XML을 이용하고 있다.
#### 4.3 JSON
- JSON (JavaScript Object Notation)은 경량 데이터 기술 언어로서 JavaScript에 있어서 오브젝트 표기법을 바탕으로 하고 있다. 다룰 수 있는 데이터형은 false/null/tree/오브젝트/배열/수치/문자열 등 일곱 가지 종류이다.
- 문자열을 JavaScript에서 간단하게 읽어올 수 있다는 점에서 XML이 사용되던 Ajax에서 JSON을 널리 이용하게 되었다.

**Comment by ChanhuiSeok** [comment]
## 10장 - 웹 콘텐츠에서 사용하는 기술

### 1. HTML
- 팀 버너스 리가 HTTP를 발표할 때 HTML의 원형도 제창되었음.
    - 1993년 NCSA에서 모자이크라는 브라우저 발표 시, 모자이크가 해석할 수 있는 HTML의 사양 정리한 것이 HTML 1.0로 공개됨
    - 이후 HTML5가 2014년에 공개되었음. 인터넷을 보면 HTML6이 나온다는 정보글들이 있지만 실제로는 아니며 정확히 정해진 바가 없다.

### 2. CSS
- HTMl 각 요소를 어떻게 표시할지 지시하는 것. 스타일 시트의 사양 중 하나이다. 문서의 구조와 디자인을 분리한다는 이념에서 만들어졌다.

### 3.  다이나믹 HTML
- 웹 페이지를 JavaScript 등의 클라이언트 사이드 스크립트로 조작해서 동적으로 변화시킨다. 이 때 DOM 이라는 구조를 사용한다.

### 4. 웹 애플리케이션
- 웹 기능을 사용해서 제공되는 프로그램을 지칭한다.
- `CGI(Common Gateway Interface)` : 웹 서버가 클라이언트에서 받은 리퀘스트를 프로그램에 전달하기 위한 구조.(동적 콘텐츠 생성) → ex: Perl, PHP, Ruby, ..
- `서블릿(Servlet)` : 서버 상에 HTML 등 동적 콘텐츠를 생성하기 위한 프로그램. Java 사양의 하나임. 위 CGI의 문제점을 해결하는 기술로 보급됨

### 5. XML
- 목적에 맞게 확장 가능한 범용적으로 사용할 수 있는 마크업, HTML보다 데이터를 기술하는 것에 특화됨

### 6. RSS/Atom
- 뉴스나 블로그의 기사 등의 갱신 정보를 송신하기 위한 문서 포맷의 총칭. 둘 다 XML을 사용하고 있다.

### 7. JSON
- JavaScript Object Notation의 줄임말. 경량 데이터 기술 언어로서 JavaScript(ECMAScript)에 있어서 오브젝트 표기법을 바탕으로 하고 있다. 단순하고 가볍게, 문자열을 JavaScript에서 간단하게 읽어올 수 있는 점에서 널리 이용하게 되었다. → 사실상 나도 가장 많이 쓰는 것

**Comment by hhhyunwoo** [comment]
# 10장. 웹 콘텐츠에서 사용하는 기술

### 웹 페이지의 대부분은 HTML로 되어 있음.

- html : Hyper Text Markup Language

### 다이나믹 HTML

- DOM
- javascript

### 웹 애플리케이션

- CGI
- 서블릿
    - 서버 상에 html 등의 동적 컨텐츠를 생성하기 위한 프로그램

### 포맷이나 언어

- XML
    - 범용적으로 사용할 수 있는 마크업 언어
- RSS/Atom
    - 뉴스나 블로그의 기사 등의 갱신 자료를 송신하기 위한 문서 포맷
