### ISSUE TITLE
11장. 웹 공격 기술

### ISSUE THREAD

**Issue by jjangsungwon** [WhiteKow/http-network-basic-study#11]

**Comment by jjangsungwon** [comment]
## 11장. 웹 공격 기술
- HTTP는 보안 상의 문제가 일어날 정도로 복잡한 프로토콜이 아니라서 프로토콜 자신이 공격 대상이 되는 경우는 거의 없다.
- 대부분 HTTP를 사용하는 서버와 클라이언트 그리고 서버 상에서 동작하는 웹 애플리케이션이 공격 대상이다. (특히 웹 애플리케이션)

### HTTP에는 보안 기능이 없다.
- HTTP에는 보안 기능이 없어서 웹 애플리케이션 인증이나 세션 관리 기능을 개발자가 설계하고 구현할 필요가 있다.
- 개발자의 설계에 따라 구현되기 때문에 보안 등급이 충분하지 못하고 취약성이 있는 웹 애플리케이션이 존재한다.
- 리퀘스트는 클라이언트에서 변조 가능

### 공격 패턴
- 능동적 공격: 공격자가 직접 웹 애플리케이션에 액세스해서 공격 코드를 보내는 타입 (ex, SQL 인젝션, OS 커맨드 인젝션)
- 수동적 공격: 함정을 이용해서 유저에게 공격 코드를 실행시키는 공격

### 출력값의 이스케이프 미비로 인한 취약성
- 클라이언트에서 체크: 입력 실수를 바로 지적해 주는 정도
- 웹 애플리케이션(서버 측)에서 체크: 입력값, 출력값 체크
- 크로스 사이트 스크립팅 (XSS, Cross-Site Scripting)
  - 취약성이 있는 웹사이트를 방문한 사용자의 브라우저에서 부정한 HTML 태그나 JavaScript 등을 동작시키는 공격
- SQL 인젝션
  - 데이터베이스에 SQL을 부정하게 실행하는 공격
  - SQL 에러 메시지가 공격의 힌트가 될 수 있다.
- OS 커맨드 인젝션
  - 웹 애플리케이션을 경유하여 OS 명령을 부정하게 실행하는 공격
- HTTP 헤더 인젝션
  - 리스폰스 헤더 필드에 개행 문자 등을 삽입함으로써 임의의 리스폰스 헤더 필드나 바디를 추가하는 수동적 공격
- 메일 헤더 인젝션
  - 메일 송신 기능에 공격자가 임의의 To 및 Subject 등의 메일 헤더를 부정하게 추가하는 공격
- 디렉토리 접근 공격
  - 디렉토리 트래버설(Directory Traversal)이란 비공개 디렉토리의 파일에 대해서 부정하게 디렉토리 패스를 가로질러 액세스하는 공격
- 리모트 파일 인클루션 
  - 스크립트의 일부를 다른 파일에서 읽어올 때 공격자가 지정한 외부 서버의 URL을 파일에서 읽게 함으로써 임의의 스크립트를 동작시키는 공격

### 웹 서버의 설정이나 설계 미비로 인한 취약점
- 강제 브라우징
  - 공개 의도가 없는 파일이 열람되게 되는 취약성
- 부적절한 에러 메시지 처리
  - 공격자에게 유익한 정보가 웹 애플리케이션의 에러 메시지에 포함되는 경우
- 오픈 리다이렉트
  - 지정한 임의의 URL로 리다이렉트 하는 기능
  - 리다이렉트되는 곳의 URL에 악의가 있는 웹 사이트가 지정된 경우 유저가 그 웹 사이트로 유도되는 취약성과 연결된다.

### 세션 관리 미비로 인한 취약성
- 세션 하이잭
  - 유저의 세션 ID를 입수해서 악용하는 것으로, 유저로 위장하는 공격
- 세션 픽세이션
  - 공격자가 지정한 세션 ID를 유저에게 강제적으로 사용하게 하는 공격 (수동적 공격, 세션 고정 공격)
- 세션 어댑션
  - PHP, ASP.NET 등에 존재하는 미지의 세션 ID를 받아들이는 기능. 세션 픽세이션의 준비 단계에 필요했었던 웹 사이트에게 세션 ID를 발행 받는 수고를 생략할 수 있다.
- 크로스 사이트 리퀘스트 포저리
  - 인증된 유저가 의도하지 않는 개인 정보나 설정 정보 등을 공격자가 설치해 둔 함정에 의해 어떤 상태를 갱신하는 처리를 강제로 실행시키는 공격 (수동적 공격)

### 기타
- 패스워드 크래킹
  - 패스워드를 논리적으로 이끌어내서 인증을 돌파하는 공격
  - 무차별 대입 공격, 사전 공격, 암호화된 패스워드 해독, 레인보우 테이블, 열쇠 입수
- 클릭 재킹
  - 투명한 버튼이나 링크를 함정으로 사용할 웹 페이지에 심어 두고, 유저에게 링크를 클릭하게 함으로써 의도하지 않은 콘텐츠에 액세스 시키는 공격 (UI Redressing)
- DoS (Denial of Service attack)
  - 서비스 제공을 정지 상태로 만드는 공격
- 백도어 (BackDoor)
  - 제한된 기능을 정규 절차를 밟지 않고 이용하기 위해 설치된 뒷문

**Comment by ChanhuiSeok** [comment]
## 11장. 웹 공격 기술

### 1. HTTP에는 보안 기능이 없다.
- 인증이나 세션 관리 기능을 개발자가 설계하고 구현할 필요가 있다. 제각각이 설계해서, 각기 다르게 구현되고, 그 결과 보안등급이 충분치 못하고 취약성이 있는 상태로 가동될 수 있다.
- 브라우저로부터 수신한 HTTP 리퀘스트 내용은 모든 클라이언트에서 변조 가능해서, 기대하고 있는 값과 다른 값이 보내질 위험이 있다.

### 2. 웹 애플리케이션에 대한 공격 패턴
- 서버를 노리는 `능동적 공격`
    - 공격자가 웹 애플리케이션에 직접 액세스하여 공격 코드를 보내는 타입. 서버 상의 리소스에 대해 직접 실행됨
    - 예 : SQL 인젝션, OS 커맨드 인젝션
- 유저를 노리는 `수동적 공격`
    - 함정을 이용해 유저에게 공격 코드를 실행시키는 공격. 공격자가 직접 웹 애플리케이션에 액세스해서 공격하는 것이 아니라 함정을 이용한다.
    - 공격자가 설치한 함정에 유저 유도 → 사용자가 걸리면 유저 브라우저나 메일 등에서 함정을 연다 → 함정에 걸리면 HTTP 리퀘스트를 공격 대상에 송신 및 공격 코드 실행 → 실행 시 유저의 쿠키 정보나 로그인 유저의 권한 악용
    - 예 : XSS(크로스 사이트 스크립팅), CSRF(크로스 사이트 리퀘스트)
    - [사이트 간 스크립팅](https://ko.wikipedia.org/wiki/%EC%82%AC%EC%9D%B4%ED%8A%B8_%EA%B0%84_%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8C%85)(XSS)을 이용한 공격이 사용자가 특정 웹사이트를 신용하는 점을 노린 것이라면, 사이트간 요청 위조(CSRF)는 특정 웹사이트가 사용자의 웹 브라우저를 신용하는 상태를 노린 것이다.

#### 1. 크로스 사이트 스크립팅(XSS)
- 취약성이 있는 웹 사이트를 방문한 사용자의 브라우저에서, 부정한 HTML 태그나 JavaScript 등을 동작시키는 공격.
- 공격자가 작성한 스크립트가 함정이 되고, 유저의 브라우저 상에서 움직이는 수동적 공격임

#### 2. SQL 인젝션
- 웹 애플리케이션을 이용 중인 데이터베이스에 SQL을 부정하게 실행하는 공격. 데이터베이스 내의 데이터 부정 열람이나 변조, 인증 회피, 데이터베이스 서버를 경유한 프로그램 실행 등이 가능할 수 있다.

#### 3. OS 커맨드 인젝션
- 웹 애플리케이션을 경유하여 OS 명령을 부정하게 실행하는 공격. 커맨드 라인에서 프로그램을 기동하는 쉘에 대해 커맨드를 보낼 수 있다.

#### 4. HTTP 헤더 인젝션
- 공격자가 리스폰스 헤더 필드에 개행 문자 등을 삽입해, 임의의 리스폰스 헤더 필드나 바디를 추가하는 수동적 공격이다.

#### 5. 메일 헤더 인젝션
- 웹 애플리케이션의 메일 송신 기능에, 공격자가 임의의 To, Subject 등의 메일 헤더를 부정하게 추가하는 공격이다.

#### 6. 디렉토리 접근 공격
- 디렉토리 트래버설(Directory Traversal) : 비공개 디렉토리 파일에 대해 부정하게 디렉토리 패스를 가로질러 액세스하는 공격. 패스 트래버설이라고 부르기도 한다.
    - 상대 경로 등을 지정해서 공개를 원치 않는 파일에 공격자가 액세스할 수 있다.

#### 7. 리모트 파일 인클루션
- 스크립트의 일부를 다른 파일에서 읽어올 때 공격자가 지정한 외부 서버의 URL을 파일에서 읽게 함으로써 임의의 스크립트를 동작시키는 공격이다. 주로 PHP에서 발생하는 취약점이다.

아래부터는 웹 서버 설정이나 설계 미비로 인한 취약성이다.

#### 8. 강제 브라우징
- 웹 서버 공개 디렉토리에 있는 파일 중, 공개 의도가 없는 파일이 열람되게 되는 취약성
- 예: SNS에서 친구 관계를 맺고 있는 유저만 내 일기에 접근할 수 있다. 그러나, 거기에 작성된 이미지의 URL을 알고 있다면 일기 액세스 권한이 없더라도 이미지를 표시할 수 있다.
즉, 일기 기능과 본문은 액세스 제어를 하고 있으나 이미지는 액세스 대상이 되어 있지 않아 발생하는 취약성이다.

#### 9. 부적절한 에러 메시지 처리(Error Handling Vulnerability)
- 공격자에게 유익한 정보가 웹 애플리케이션의 에러 메시지에 포함된다는 취약성
    - 예 : 로그인할 때 ‘등록되어 있지 않는 메일 주소입니다.’ 라고 나오면 입력한 메일 주소가 등록되었는지 여부를 확인할 수 있으므로 공격의 힌트로 사용되지 않게 ‘인증 에러’ 정도로 표시하면 좋다.
    - 예2 : 에러 메시지에서 데이터베이스의 에러가 표시되는 경우, 관련한 정보가 나오며 공격 힌트가 될 수 있다. 상세한 에러 메시지를 제한하거나, 커스텀 에러 메시지를 이용하도록 한다.

#### 10. 오픈 리다이렉트
- 지정한 임의의 URL로 리다이렉트하는 기능이다. 악의가 있는 웹 사이트로 유도되는 취약성과 연결될 수 있다.

아래부터는 세션 관리 미비로 인한 취약성이다.

#### 11. 세션 하이잭
- 공격자가 어떠한 방법으로 유저 세션 ID를 압수해서 악용하는 것. 유저로 위장하는 공격이다.

#### 12. 세션 픽세이션
- 공격자가 지정한 세션 ID를 유저에게 강제적으로 사용하게 하는 공격. 세션 고정 공격이라고도 불린다. 세션 하이잭과는 구분된다.

#### 13. 크로스 사이트 리퀘스트 포저리(CSRF)
- 인증된 유저가 의도하지 않는 개인 정보, 설정 정보 등을 공격자가 설치해 둔 함정에 의해 어떤 상태를 갱신하는 처리를 강제로 실행시키는 공격.
    - 인증된 유저의 권한으로 설정 정보 갱신, 상품 구입, 게시판 글 작성 등의 영향을 받을 수 있음

아래부터는 그 외 다른 공격 방식들이다.

#### 14. 패스워드 크래킹
- 패스워드를 논리적으로 이끌어내 인증을 돌파하는 공격.
    - 네트워크 경유로 패스워드 시행 : 무차별 대입 공격(Brute-force Attack), 사전 공격(Dictionary Attack)
    - 사전 공격은 패스워드 후보(사전)를 준비해 두고 시험해 보면서 인증을 돌파하는 공격이다. 예를 들어, 4자리 비밀번호는 주로 생일을 사용하는 가능성이 높으므로 0101~1231로 후보를 압축해서 테스트한다.
- 암호화된 패스워드를 해독
    - 해시 함수나 salt 등의 방법으로 패스워드를 암호화를 하게 되는데, 여기로부터 평문을 도출해 내면 공격자가 패스워드를 탈취하게 되는 것이다.
    - 평문을 도출하는 방법
        - 무차별 대입 공격, 사전 공격에 의한 유추
        - 레인보우 테이블 : 평문과 그에 대응하는 해시 값으로 구성된 데이터베이스 테이블. 사전에 거대한 테이블을 만들어 무차별 대입 공격, 사전 공격 등에 걸리는 시간을 단축하는 테크닉이다.
        - 열쇠 입수 : 패스워드가 공통키 암호 등으로 암호화되어 있다면, 암호화에 사용한 키를 어떤 방법으로든 입수하여 복호화할 수 있다.
        - 암호 알고리즘의 취약성

#### 15. 클릭 재킹
- 투명한 버튼이나 링크를 함정으로 사용할 웹 페이지에 심어 두고, 유저에게 링크를 클릭하게 한다. UI Redressing이라고 부르기도 한다.

#### 16. DoS 공격
- 서비스 제공을 정지 상태로 만드는 공격이다. 웹 사이트뿐만 아니라 네트워크 기기나 서버 등을 대상으로 공격하는 경우도 있다.
    - 액세스를 집중시켜 부하를 걸어 리소르를 다 소비하게 해, 사실상 서비스를 정지 상태로 만듬
    - 취약성을 공격해 서비스를 정지시킴
    - 여러 대의 컴퓨터에서 실행하는 DoS 공격은 DDoS 공격이라고 부른다. (+인터넷 트래픽의 폭주로 공격 대상이나 그 주변 인프라를 압도하여 공격 대상 서버나 서비스, 네트워크의 정상적인 트래픽을 방해하는 악의적인 시도. 출처 : cloudflare)

#### 17. 백도어
- 제한된 기능을 정규 절차를 밟지 않고 이용하기 위해 설치된 뒷문이다. 본래 정해진 제한을 초과한 기능을 이용하는 것이 가능해진다.
    - 개발 단계에 디버그용으로 추가한 백도어
    - 개발자가 자기 자신의 이익을 위해 추가한 백도어
    - 공격자가 어떠한 방법을 써서 설치한 백도어

**Comment by hhhyunwoo** [comment]
# 11장. 웹 공격 기술

- HTTP 자체는 복잡한 프로토콜이 아니기 때문에 프로토콜 자신이 공격 대상이 되는 경우는 거의 없음.
- HTTP를 사용하는 서버와 클라이언트 그리고 서버 상에서 동작하는 웹 애플리케이션 등의 리소스가 공격 대상이 됨.

## 출력 값의 이스케이프 미비로 인한 취약성

### 크로스 사이트 스크립팅

- 취약한 html 태그나 javascript 등을 동작시키는 공격

### SQL 인젝션

- 부정한 sql을 실행함

### os 커맨드 인젝션

- open, mv 등과 같은 커맨드를 로컬에서 실행하게 함

### HTTP 헤더 인젝션

- 공격자가 리스폰스 헤더 필드에 개행 문자 등을 삽입함으로써 임의의 리스폰스 헤더 필드나 바디를 추가하는 수동적 공격

### 메일 헤더 인젝션

- 메일 송신 기능에 공격자가 임의의 to 및 subject 등의 메일 헤더를 부정하게 추가하는 공격

### 디렉터리 접근 공격

- 부정하게 디렉터리 패스를 가로질러 엑세스 하게 하는 공격

### 리모트 파일 인클루션

- 스크립트의 일부를 다른 파일에서 읽어올 때 공격자가 지정한 외부 서버의 url을 파일에서 읽게함으로써 하는 공격

## 웹 서버의 설정이나 설계 미비로 인한 취약성

### 강제 브라우징

- 공개 의도가 없는 파일이 열람되게 되는 취약성

## 세션 관리 미비로 인한 취약성

### 세션 하이잭

### 세션 픽세이션

- 공격자가 지정한 세션 id를 유저에게 강제적으로 사용하게 하는 공격

### 크로스 사이트 리퀘스트 포저리

- CSRF
- 인증된 유저가 의도하지 않은 개인 정보나 설정 정보 등을 공격자가 설치해둔 함정에 의해 어떤 상태를 갱신하는 처리를 강제로 실행시키는 공격

## 기타

### 패스워드 크래킹

- 인증돌파

### 클릭재킹

### DoS 공격

### 백도어
