### ISSUE TITLE
3장. HTTP 정보는 HTTP 메시지에 있다

### ISSUE THREAD

**Issue by jjangsungwon** [WhiteKow/http-network-basic-study#3]

**Comment by jjangsungwon** [comment]
## 3장. HTTP 정보는 HTTP 메시지에 있다.
클라이언트에서 보내는 리퀘스트와 서버에서 보내는 리스폰스가 어떻게 동작하는지 배울 수 있었다.

### HTTP 메시지
- 메시지 헤더와 메시지 바디로 구성되어 있다.
- 최초에 나타나는 개행 문자(CR+LK)로 메시지 헤더와 메시지 바디를 구분한다.
- 메시지 바디는 항상 존재한다고는 할 수 없다. GET, OPTIONS와 같이 리소스를 가져오는 요청들은 일반적으로 바디를 필요로 하지 않는다고 한다.

### 리퀘스트 메시지와 리스폰스 메시지의 헤더
- 리퀘스트 메시지: 리퀘스트 라인, 리퀘스트 헤더 필드, 일반 헤더 필드, 엔티티 헤더 필드 그 외
- 리스폰스 메시지: 리퀘스트 라인 대신 상태 라인이 들어있고 나머지는 리퀘스트 메시지와 동일하다.
  - 리퀘스트 라인: 사용 메소드, URI, HTTP 버전
  - 상태 라인: 상태 코드, 설명, HTTP 버전
  - 헤더 필드: 여러 조건과 속성 (일반 헤더, 리퀘스트 헤더, 리스폰스 헤더, 엔티티 헤더)
  - 그 외: HTTP의 RFC에는 없는 헤더 필드 (ex, 쿠키) [RFC LINK](https://developer.mozilla.org/ko/docs/Web/HTTP/Resources_and_specifications)
![image](https://user-images.githubusercontent.com/41226054/195734751-d08bec92-11fb-4a39-8ef3-535d38e2e39b.png)


### 인코딩
- 인코딩(변환)을 통해 데이터 전송 효율을 높일 수 있다. 하지만, 컴퓨터에서 인코딩 처리를 해야 하기 때문에 CPU 등의 리소스는 보다 많이 소비하게 된다. -> 메시지 전송 측면에서는 효율적이지만 컴퓨터 메모리 측면에서는 비효율적? 하지만 메모리는 이러한 일을 하기 위해서 존재하는 거니까 비효율적은 아니고 아무튼 메모리는 더 쓴다!
- 콘텐츠 로딩: 압축하여 전송
- 청크 전송 코딩: 분해하여 전송

### 메시지 vs 엔티티
- 메시지: HTTP 통신의 기본 단위. 옥텟 시퀀스로 구성. 엔티티 바디를 운반하는 작업
- 엔티티: 리퀘스트와 리스폰스의 페이로드로 전송되는 정보. 엔티티 헤더와 바디 필드로 구성

### 멀티파트
- 여러 데이터 전송
- MIME(Multipurpose Internet Mail Extensions: 다목적 인터넷 메일 확장 사양): 바이너리 데이터를 아스키(ASCII) 문자열에 인코딩하는 방법과 데이터 종류를 나타내는 방법을 규정하고 있다. MIME의 확장 사양에 있는 멀티파트를 사용하면 텍스트, 영상, 이미지 여러 데이터를 함께 전송할 수 있다.
- multipart/form-data: Web 폼으로부터 파일 업로드에 사용된다.
- multipart/byteranges: 상태 코드 206(Partial Content) 리스폰스 메시지가 복수 범위의 내용을 포함할 때 사용된다.
- HTTP 메시지로 멀티파트를 사용할 때에는 Content-type 헤더 필드를 사용한다.
- 멀티파트 각각의 엔티티를 구분하기 위해 boundary 문자열을 사용한다.

### 레인지 리퀘스트
- 리줌(resume) 이전에 다운로드를 한 곳에서부터 다운로드를 재개할 수 있다.
- 레인지 리퀘스트: 범위를 지정하여 리퀘스트를 요청
  - 리스폰스는 206 Partial Content 메시지가 온다.
  - 복수 범위의 레인지 리퀘스트에 대한 리스폰스는 multipart/byteranges 이다.
  - 서버가 레인지 리퀘스트를 지원하지 않으면 상태 코드 200 OK 메시지로 완전한 엔티티가 온다.

### 콘텐츠 네고시에이션
- 같은 URI에 액세스할 때 다양한 언어를 지원할 수 있는 구조를 콘텐츠 네고시에이션(Content Negotiation)이라고 한다.
- 언어와 문자 세트, 인코딩 방식 등을 기준으로 제공해야 하는 리소스를 판단한다. (Accept 관련 헤더 필드)
- 서버 구동형 네고시에이션: 서버 측에서 콘텐츠 네고시에이션 결정
- 에이전트 구동형 네고시에이션: 클라이언트 측에서 콘텐츠 네고시에이션 결정
- 트랜스페어런트 네고시에이션: 서버와 클라이언트가 각각 콘텐츠 네고시에이션 결정
- 서로 다른 언어를 제공하는 페이지는 동일한 코드가 여러 개 있는 형식일까? (참고: 다양한 국가의 유저가 사이트에서 동일한 감정을 느낄 수 있도록 구현하는 게 쉽지 않다고 합니다. 단순 번역이랑 차원이 다르다고 하네요.)

**Comment by hhhyunwoo** [comment]
## HTTP 메시지

```bash
<REQUEST>

GET / HTTP/1.1
Host: developer.mozilla.org
Accept-Language: fr
```

```bash
<RESPONSE>

HTTP/1.1 200 OK
Date: Sat, 09 Oct 2010 14:28:02 GMT
Server: Apache
Last-Modified: Tue, 01 Dec 2009 20:18:22 GMT
ETag: "51142bc1-7449-479b075b2891b"
Accept-Ranges: bytes
Content-Length: 29769
Content-Type: text/html

<!DOCTYPE html>… (here come the 29769 bytes of the requested web page)
```

HTTP 메시지에는 리퀘스트 메시지와 리스폰스 메시지가 있음. 

## 메시지 바디와 엔티티 바디

- 메시지 바디의 역할은 리퀘스트랑 리스폰스에 대한 엔티티 바디를 운반하는 일
- 엔티티 바디 : Payload. 엔티티 헤더 필드와 엔티티 바디로 구성됨

## 인코딩

- 콘텐츠 코딩 : 엔티티 정보를 유지한테 압축. 그 후에 클라이언트로 보냄
- 청크 전송 코딩 : 청크로 나눠서 전송 (엔티티 바디 끝에는 0을 표시)

## 멀티파트

- MIME : 여러 다른 데이터를 다루기 위한 기능을 사용하고 있음
- 하나의 메시지 바디 내부에 엔티티를 여러 개 포함시켜 보낼 수 있다.
    - multipart/form-data
    - multipart/byteranges

## Range request

- 엔티티 범위를 지정(헤더)해서 리퀘스트 할 수 있음

**Comment by ChanhuiSeok** [comment]
## 3장
HTTP에서 교환하는 정보를 HTTP 메시지라고 부른다.
- HTTP 메시지는 메시지 헤더와 메시지 바디로 구성되어 있다.

HTTP로 데이터를 전송할 겨우 전송할 때 인코딩을 실시해 전송 효율을 높일 수 있다.
- 메시지 : HTTP 통신의 기본 단위. 옥텟 시퀀스로 구성되고 통신을 통해 전송됨
- 엔티티 : 리퀘스트와 리스폰스의 페이로드로 전송되는 정보. 엔티티 헤더 필드와 엔티티 바디로 구성된다.

HTTP에는 콘텐츠 코딩이라는 기능이 있다.
- 엔티티에 적용하는 인코딩을 가리키며, 엔티티 정보를 유지한 채로 압축한다. 콘텐츠 코딩된 엔티티는 수신한 클라이언트 측에서 디코딩한다.

HTTP 통신에선 리퀘스트했던 리소스 전부에서, 엔티티 바디의 전송이 완료되지 않으면 브라우저에 표시되지 않는다. -> 그래서 청크 전송 코딩이 생겨남

MIME

- 다목적 인터넷 메일 확장 사양으로 불리는 포맷이다.
> (참고1) 이메일과 함께 동봉할 파일을 텍스트 문자로 전환해서 이메일 시스템을 통해 전달하기 위해 개발되었기 때문에 이름에 Internet Mail Extension 이지만 현재는 웹을 통해서 여러 형태의 파일을 전달하는 데에도 쓰이고 있다.
> (참고2) 클라이언트에게 전송된 문서의 다양성을 알려주기 위한 메커니즘입니다: 웹에서 파일의 확장자는 별 의미가 없습니다. 그러므로, 각 문서와 함께 올바른 MIME 타입을 전송하도록, 서버가 정확히 설정하는 것이 중요합니다. 브라우저들은 리소스를 내려받았을 때 해야 할 기본 동작이 무엇인지를 결정하기 위해 대게 MIME 타입을 사용합니다.
- MIME의 확장 사양에 있는 멀티파트(Multipart)라고 하는 여러 다른 종류의 데이터를 수용하는 방법이 있다.

레인지 리퀘스트

- 엔티티의 범위를 지정하여 리퀘스트하는 것을 레인지 리퀘스트라고 한다. Range 헤더 필드를 사용해서 리소스의 바이트 레인지를 지정할 수 있다.

콘텐츠 네고시에이션

- 동일한 URI에서 리소스의 서로 다른 버전을 서브하기 위해 사용되는 메커니즘으로, 사용자 에이전트가 사용자에게 제일 잘 맞는 것이 무엇인지(예를 들어, 문서의 언어, 이미지 포맷 혹은 컨텐츠 인코딩에 있어 어떤 것이 적절한지)를 명시할 수 있습니다. (`mdn web docs 참고함`)
