### ISSUE TITLE
4장. 결과를 전달하는 HTTP 상태 코드

### ISSUE THREAD

**Issue by jjangsungwon** [WhiteKow/http-network-basic-study#4]

**Comment by hhhyunwoo** [comment]
## HTTP Status Code

1xx : 리퀘스트를 받아들여 처리중

2xx: 리퀘스트를 정상적으로 처리했음

3xx: 추가 동작 필요 

4xx: 클라이언트 에러

5xx: 서버 에러

- 503일 경우 retry-After 헤더 필드를 사용해서 상태 해소까지 여유 시간을 둘 수 있음

**Comment by jjangsungwon** [comment]
## 4장. 결과를 전달하는 HTTP 상태 코드
클라이언트가 HTTP 리퀘스트를 보낸 결과, 즉 서버가 정상적으로 처리되었는지 혹은 에러가 발생했는지를 알려주는 HTTP 상태 코드를 배우는 장이다.

### 상태 코드
- 3자리 숫자와 설명으로 나타낸다.
- 첫 번째 숫자는 리스폰스의 클래스를 의미한다. 나머지 2자리는 분류가 없다.
- 1xx: Informational, 리퀘스트를 받아들여 처리 중
- 2xx: Success: 리퀘스트를 정상적으로 처리했음
- 3xx: Redirection: 리퀘스트를 완료하기 위해서 추가 동작이 필요
- 4xx: Client Error: 클라이언트 에러
  - 400: Bad Request, 리퀘스트 구문이 잘못된 경우. 브라우저는 이것을 200 OK와 같이 취급함
  - 404: Not Found, 리퀘스트한 리소스가 서버에 없는 경우. 리퀘스트를 거부하고 싶은 이유를 밝히고 싶지 않은 경우에도 사용함
- 5xx: Server Error, 서버 에러
  - 503: Service Unavailable, 서버가 과부하 상태 혹은 점검 중이라서 현재 리퀘스트를 처리할 수 없음을 표시. 이 상태를 해소하기까지 시간이 걸리는 경우 Retry-After 헤더 필드로 클라이언트에 전달 가능
- 상태 코드가 현재 상황가 불일치할 수도 있다.

**Comment by ChanhuiSeok** [comment]
## 4장

HTTP 상태코드는 개발하면서 많이 접하게 된다. 서버로부터 리퀘스트 결과를 전달하는 역할을 한다.
3자리 숫자로 이루어지는데, 맨 앞 숫자가 어떤 것을 의미하는지 정도는 정확하게 알아두면 좋겠다.

- 1xx : Informational - 리퀘스트를 받아들여 처리중
- 2xx : success - 리퀘스트 정상 처리 완료(성공)
- 3xx : Redirection - 리퀘스트 완료 위해 추가 동작 필요
- 4xx : Client Error - 서버는 리퀘스트 이해 불가(실패)
- 5xx : Server Error - 서버는 리퀘스트 처리 실패

3xx 리스폰스 : 리퀘스트가 정상적으로 처리를 종료하기 위해, 브라우저 측에서 특별한 처리를 수행해야 함을 나타낸다.

서버의 응답값 정의 시 이 상태코드의 의미에 맞게 잘 내려주는 것이 좋다고 생각한다.
