### ISSUE TITLE
5장. HTTP와 연계하는 웹 서버

### ISSUE THREAD

**Issue by jjangsungwon** [WhiteKow/http-network-basic-study#5]

**Comment by hhhyunwoo** [comment]
## Virtual Host

- 물리 서버 1대에 여러개의 호스트를 등록해서 사용할 수 있음
- 이를 위해서 요청 시 호스트 명과 도메인 명을 완전하게 포함한 URI를 지정하거나, HOST 헤더필드에서 지정해야함

## 프록시

- 기본적으로 클라이언트로부터 받은 리퀘스트를 다른 서버에 전송하는 것
- Nginx
    - reverse proxy
    ![image](https://user-images.githubusercontent.com/37402136/195892002-9124417e-6be4-4867-b003-c401f7d6d378.png)
    - nginx 는 Proxy, Caching, Web Application Firewall, Load Balancer, 엑세스 제한 등의 기능을 가지고 있다.
    - Round Robin / Least Connection / IP Hash / Generic Hash 등 여러 방법으로 Load Balancing 이 가능함.
    ![image](https://user-images.githubusercontent.com/37402136/195892058-2348dd4b-a4fc-4eff-b737-3db7cf1560d1.png)
    - 모든 경로로 들어오는 모든 요청을 대상으로 Load Balancing 과 Health Check를 한다.

### 캐싱 프록시

- 리스폰스를 중계하는 때에 프록시 서버 상에 리소스 캐시를 보존해 두는 타입의 프록시

## 게이트웨이

- 그 다음에 있는 서버가 HTTP 서버 이외의 서비스를 제공하는 서버가 됨.
- 클라와 서버 사이의 암호화 등으로 안전성을 높이기도 함
- 예)SQL,,

## 터널

- 요구에 따라서 다른 서버와의 통신 경로를 확립함
- 해석 하지 않고 그대로 중계함

## 캐시

### 캐시 서버

- 프록시 서버의 하나
- 리스폰스를 중계할 때 리소스 사본을 가지고 있음
- 유효기간 존재

**Comment by jjangsungwon** [comment]
## 5장. HTTP와 연계하는 웹 서버
### 가상 호스트 (Virtual Host)
- 물리적으로는 서버가 1대이지만 가상으로 여러 대가 있는 것처럼 설정
- 리퀘스트가 서버에 도착한 시점에는 IP 주소를 기준으로 액세스함. 즉, 1대의 서버 안에 다른 도메인이 있을 경우 IP 주소만으로는 구분할 수 없음. -> 호스트명과 도메인 명을 완전하게 포함한 URI를 지정하거나, 반드시 Host 헤더 필드에서 지정해야 함

### 프록시 (Proxy)
- 서버와 클라이언트의 양쪽 역할
- 클라이언트 리퀘스트를 서버에 전송
- 서버 리스폰스를 클라이언트에 전송
- Via 헤더 필드에 경유한 호스트 정보 추가함
- 캐시를 활용한 네트워크 대역 효율적 활용, 액세스 제한 등에 활용
- 캐싱 프록시: 프록시 서버 상에 리소스 캐시 보존
- 투명 프록시: 메시지 변경을 하지 않는 타입 <-> 비투과 프록시

### 게이트웨이 (Gateway)
- 다른 서버를 중계하는 서버
- HTTP 서버와 통신하고 있는 경우 게이트웨이를 통해 HTTP 서버 이외의 서비스를 제공하는 서버와 연결 가능
- ex) 데이터베이스 접속, 쇼핑 사이트의 신용 결제 시스템

### 터널 (Tunnel)
- 다른 서버와의 통신 경로를 확립
- HTTP 리퀘스트를 해석하려고 하지 않음
- 통신하고 있는 양쪽 끝의 접속이 끊어질 때 종료

### 리소스를 보관하는 캐시
- 캐시: 프록시 서버와 클라이언트 로컬 디스크에 보관된 리소스 사본
- 같은 데이터를 서버에 전송할 필요 없음. 통신량과 통신 시간 절약
- 유효기간 존재. 주기적으로 캐시의 유효성도 확인함
- 클라아이언트 측에도 캐시 존재

**Comment by ChanhuiSeok** [comment]
## 5장

### 가상 호스트
- 하나의 HTTP 서버에 여러 개의 웹 사이트를 실행할 수 있다. (예: 웹 호스팅을 제공하고 있는 사업자는 1대의 서버에 여러 고객의 웹 사이트를 넣을 수 있음)
- 즉 서버 IP 주소 하나로 다른 여러 호스트를 운영하는 형태이다.
- 도메인명은 DNS에 의해 IP 주소로 변환되고 나서 액세스하게 됨. 즉, 리퀘스트가 서버에 도착한 시점에는 IP 주소를 기준으로 액세스하게 된다.
만약 같은 서버 안에 같은 IP 주소의 웹 서버에서 여러 도메인이 실행되고 있을 때 DNS로 이름을 해결하면, 어느 쪽도 같은 수신인이 되어 버린다.
그러므로 http 리퀘스트 시에는 호스트명과 도메인 명을 완전하게 포함한 URI를 지정하거나 반드시 Host 헤더 필드에서 지정해야 한다.
<img width="600" alt="스크린샷 2022-10-15 오전 8 42 19" src="https://user-images.githubusercontent.com/45116772/195959022-ec6cfd04-5a8a-4c4f-8d16-38b08af7373a.png">
(출처) https://foxydog.tistory.com/30

### 프록시, 게이트웨이, 터널
- 클라이언트와 서버 이외에, 이들을 서버에 연계할 수 있음. (클라이언트 - 서버 사이에 위치한다고 보면 됨)
- 프록시 : 서버와 클라이언트 양 쪽 역할을 하는 중계 프로그램. 클라이언트로부터 리퀘스트를 받아 서버로 송신하고, 서버로부터 리스폰스를 받아 클라이언트에게 전송
    - 캐시를 사용해 네트워크 대역을 효율적으로 사용하거나, 조직 내 특정 웹 사이트에 대한 액세스 제한, 액세스 로그 획득 정책을 지키려는 목적 등으로 사용
    - 캐싱 프록시와 투명 프록시로 구분
    - 캐싱 프록시는 프록시 서버 상에 리소스 캐시를 보존해 두는 타입, 같은 리소스에 리퀘스트가 오면 프록시 캐시로부터 리스폰스로 돌려줌
    - 투명 프록시는 리퀘스트와 리스폰스 중계 시 메시지 변경을 하지 않는 타입. 반대로 변경을 가하는 프록시는 비투과 프록시
- 게이트웨이 : 다른 서버를 중계하는 서버. 클라이언트로부터 수신한 리퀘스트를 리소스를 보유한 서버인 것처럼 수신한다.
    - 동작은 프록시와 유사하다. 게이트웨이 다음에 있는 서버는 HTTP 서버 이외의 서비스를 제공하는 서버가 된다. **즉, HTTP 트래픽을 다른 프로토콜로 변환하기 위해 사용한다.**
- 터널 : 서로 떨어진 두 대의 클라이언트와 서버 사이를 중계하며 접속을 주선하는 중계 프로그램.
    - 다른 서버와의 통신 경로를 확립한다. 이 때 클라이언트는 SSL과 같은 암호화 통신으로 서버와 안전하게 통신을 하기 위해 터널을 사용한다.
    - 터널 자체는 HTTP 리퀘스트를 해석하려고 하지 않는다. 터널 자체는 투명한 존재여서 클라이언트가 너무 의식할 필요는 없다.

### 캐시
- 프록시 서버와 클라이언트 로컬 디스크에 보관된 리소스 사본. 캐시를 사용하면 리소스를 가진 **서버에 대한 액세스를 줄이는 것이 가능하므로, 통신량과 통신 시간을 절약**할 수 있다.
- 캐시 서버는 프록시 서버의 일종이다. 캐시를 이용해서, 같은 데이터를 몇 번이고 오리진 서버에 전송할 필요가 없어진다.
- 캐시는 유효기간이 있어서 같은 리소스 리퀘스트에 대해 항상 캐시를 돌려 준다고는 할 수없다.
- 클라이언트가 사용하는 브라우저에서도 캐시를 가질 수 있다. 이들을 브라우저에서는 `임시 파일`이라고 부른다.
