### ISSUE TITLE
6장. HTTP 헤더

### ISSUE THREAD

**Issue by ChanhuiSeok** [WhiteKow/http-network-basic-study#6]

**Comment by ChanhuiSeok** [comment]
### 6장
- HTTP 메시지 헤더
  - HTTP 프로토콜의 리퀘스트, 리스폰스에는 반드시 메시지 헤더가 포함되어 있음
  - 헤더에는 클라이언트와 서버 처리에 필요한 주요 정보가 담김

- HTTP 헤더 필드
  - 용도에 따라 4종류로 구분 : 일반적 헤더 필드, 리퀘스트 헤더 필드, 리스폰스 헤더 필드(서버->클라), 엔티티 헤더 필드
  - HTTP/1.1 헤더 필드에 47종류가 정의되어 있음 (RFC2616에 정의됨)
    - RFC2616에 정의된 47종류만 있는 것은 아니고, 쿠키와 Set-Cookie, Content-Disposition 등도 있음
  - `End-to-end` 헤더 : 리퀘스트/리스폰스 최종 수신자에게 전달되어야 함
  - `Hop-by-hop` 헤더 : 단일 전송에 대해서만 유효하고, 프록시에 의해 재전송되거나 캐시되지 않음

- (1) HTTP/1.1 일반 헤더 필드 : 리퀘스트, 리스폰스 메시지 양쪽에서 사용되는 헤더이다.
  - Cache-Control 헤더 : [디렉티브](https://developer.mozilla.org/ko/docs/Web/HTTP/Headers/Cache-Control#%EB%94%94%EB%A0%89%ED%8B%B0%EB%B8%8C)로 불리는 명령을 사용해 캐싱 동작 지정
  - Connection 헤더 필드 : 프록시에 더 이상 전송하지 않는 헤더 필드 지정 / 지속적 접속 관리
  프록시 서버에 더 이상 전송하지 않는 헤더 필드(`hop-by-hop` 헤더)를 지정할 수 있음

- (2) 리퀘스트 헤더 필드
  - 클라이언트->서버로 송신된 리퀘스트 메시지에 사용되는 헤더. 리퀘스트의 부가 정보, 클라이언트 정보, 리스폰스의 콘텐츠에 관한 우선순위 등을 추가
  - Accept, Accept-Charset, Accept-Encoding, **Authorization**,  등이 있다.

- (3) 리스폰스 헤더 필드
  - 서버->클라이언트로 송신되는 리스폰스 메시지에 사용되는 헤더.
  - Age 헤더 필드 : 얼마나 오래 전에 오리진 서버에서 리스폰스가 생성되었는지 전달(초 단위).
 
- (4) 엔티티 헤더 필드
  - 리퀘스트 및 리스폰스 메시지에 포함된 엔티티에서 사용되는 헤더. `콘텐츠 갱신 시간`같은 엔티티 관련 정보를 포함한다.
  - 엔티티 : 리퀘스트, 리스폰스의 페이로드로 전송되는 정보이다. 엔티티 헤더 필드와 엔티티 바디로 구성된다.
  - Allow: 리소스가 지원하는 메소드 집합을 나열함. 어떤 요청 메소드를 사용할 수 있는지 알리기 위해 서버가 [405](https://developer.mozilla.org/ko/docs/Web/HTTP/Status/405) Method Not Allowed 상태코드로 응답할 경우에 이 헤더를 반드시 보내야 한다. ([mdn docs](https://developer.mozilla.org/ko/docs/Web/HTTP/Headers/Allow))
  - Content-Range : 범위를 지정해 일부분만 리퀘스트하는 Range 리퀘스트에 대해 응답을 할 때 사용한다.
  
 - 쿠키를 위한 필드 : RFC 6265에서 `넷스케이프`에 의한 사양을 디팩토 스탠다드(사실상 표준)으로 정해서 쿠키 사양을 재정의했음
   - Set-Cookie 헤더 필드 : 서버가 클라이언트(브라우저)에 쿠키를 전송하기 위해 사용함.
   - Cookie 헤더 필드 : 클라이언트가 HTTP 상태 관리 지원을 원할 때, 서버로부터 수신한 쿠리를 이후 리퀘스트에 포함해서 전달함.

**Comment by hhhyunwoo** [comment]
## HTTP 메시지 헤더

- HTTP 프로토콜의 리퀘스트와 리스폰스에는 반드시 메시지 헤더가 포함되어있다.

### General 헤더 필드

- 리퀘스트와 레스폰스 메시지 둘 다 사용되는 헤더
- Cache-control, Connection,,,

### Request 헤더 필드

- 클라이언트 측에서 서버 측으로 송신할 때 사용되는 헤더
- Accept, Accept-Charset ,,,

### Response 헤더 필드

- 서버 측에서 클라이언트 측으로 송신할 떄 사용
- Accept-Ranges, Age ,,,

### Entity 헤더 필드

- 리퀘스트 메시지와 리스폰스 메시지에 포함된 엔티티에 사용되는 헤더
- 콘텐츠 갱신 시간 등의 엔티티에 관한 정보 부가
- Allow, Content-Encoding …

- E2E 헤더 : 최종 수신자에게 전송됨. 캐시에서 보존되어야 함
- Hop by hop 헤더 : 한 번 전송에 대해서만 유효함. 캐시와 프록시에 의해 전송되지 않는 것도 있음

**Comment by jjangsungwon** [comment]
## 6장. HTTP 헤더
- 메시지 헤더, 바디로 구성
- 메시지 헤더: 클라이언트와 서버 처리에 필요한 주요 정보
- 메시지 바디: 사용자와 리소스를 필요로 하는 정보

### HTTP 헤더 필드 구조
- 헤더 필드 명과 필드 값으로 구성 (콜론 `:` 으로 나뉘어져 있음)

### 일반적 헤더 필드
- 리퀘스트, 리스폰스 메시지 둘 다 사용하는 헤더

### 리퀘스트 헤더 필드
- 클라이언트 측에서 서버 측으로 송신된 리퀘스트 메시지에 사용되는 헤더

### 리스폰스 헤더 필드
- 서버 측에서 클라이언트 측으로 송신한 리스폰스 메시지에 사용되는 헤더
- ETag: 엔티티 태그, 일의적으로 리소스를 특정하기 위한 문자열을 전달
  - 강력한 ETag: 엔티티가 조금이라도 다르면 반드시 값 변화
  - 약한 ETag: 리소스가 같다는 것만을 나타냄. 값의 앞부분에 `W/`가 붙음 

### 엔티티 헤더 필드
- 리퀘스트, 리스폰스 메시지에 포함된 엔티티에 사용되는 헤더 (ex, 콘텐츠 갱신 시간)
- End-to-end: 최종 수신자에게 전송
- Hop-by-hop: 한 번 전송에 대해서만 유효하고 캐시와 프록시에 의해서 전송되지 않는 것도 포함

### HTTP/1.1 이외의 헤더 필드
- Set-Cookie, Content-Disposition ...

### 쿠키를 위한 헤더 필드
- Set-Cookie: 상태 관리 개시를 위한 쿠키 정보
- Cookie 헤더 필드: 서버에서 수신한 쿠키 정보
- Expires: 쿠키를 송출할 수 있는 유효 기간
- Path: 쿠키 송출 범위 한정
- Domain: 지정된 도메인 명은 후방 일치가 됨. 명시적으로 여러 도메인에 대해서 쿠키를 송출하는 경우를 제외하고 domain 속성은 지정하지 않는 쪽이 안전
- secure: HTTPS에서 열렸을 때에만 쿠키 송출을 제한하기 위해서 지정
- HttpOnly: 자바스크립트를 경유해서 쿠키를 취득하지 못하도록 하는 쿠키의 확장 기능
- <img width="1475" alt="스크린샷 2022-10-22 오전 8 13 54" src="https://user-images.githubusercontent.com/41226054/197303783-c9b3178d-6798-4ef3-aadf-9e3e8b6f65a4.png">
