### ISSUE TITLE
7장. 웹을 안전하게 하는 HTTPS

### ISSUE THREAD

**Issue by ChanhuiSeok** [WhiteKow/http-network-basic-study#7]

**Comment by ChanhuiSeok** [comment]
## 7장 HTTPS

### HTTP의 약점
  - 평문 통신이라 도청 가능, 통신 상대를 확인하지 않아 위장 가능, 완전성을 증명할 수 없어서 변조 가능

#### 평문 통신이라 도청 가능
  - HTTP를 사용한 리퀘스트, 리스폰스는 암호화하는 기능이 없어서 평문으로 메시지를 보내게 된다.
  - TCP/IP 구조의 통신 내용은 전부 통신 경로 도중에 엿볼 수 있는 구조. 즉, 도청 가능한 네트워크이다. 그러므로 암호화되지 않은 HTTP는 이러한 약점이 있다.

도청으로부터 정보를 지키기 위해, `암호화`를 한다.
- (1) 통신 암호화
   - HTTP에는 암호화 구조가 없으나, **SSL이나 TLS라는 다른 프로토콜을 조합해** HTTP의 통신 내용을 암호화할 수 있다.
   - SSL 등을 이용해 안전한 통신로 확립 후, 그 통신로로 HTTP 통신을 한다. 이를 HTTPS라 부른다.
- (2) 콘텐츠 암호화
  - 통신하고 있는 콘텐츠 내용 자체를 암호화하는 방법. HTTP 메시지에 포함되는 콘텐츠만 암호화하는 것.
  메시지 바디에 들어가는 콘텐츠를 암호화한다. 메시지 헤더는 암호화되어 있지 않다.
  이 방법은 클라이언트와 서버가 콘텐츠 암호화 및 복호화 구조를 가지고 있는 것이 전제되므로 평상시 유저가 사용하는 브라우저나 웹 서버에서는 이용이 힘들다.

#### 통신 상대를 확인하지 않아 위장 가능
- HTTP에 의한 통신은 상대가 누구인지 확인하는 처리가 없다. 따라서 누구든 리퀘스트를 보낼 수 있고, 리퀘스트가 오면 상대가 누구든 서버는 무언가의 리스폰스를 반환한다. -> 상대를 확인하지 않는 것이 약점
- HTTP는 통신 상대를 확인할 수 없지만 SSL로 상대를 확인할 수 있다.
  - 즉, SSL은 **암호화뿐만 아니라 상대를 확인하는 수단**으로 증명서(인증서)를 제공한다.
  - 증명서(인증서)는 신뢰할 수 있는 제3자 기관에 의해 발행되어서 서버나 클라이언트가 실재함을 증명하고, 인증서 위조는 기술적으로 상당히 어렵다.
  - 통신 상대의 서버나 클라이언트가 가진 **증명서**를 확인해서 통신 상대가 내가 원하는 상대인지 판단 가능하다.

#### 완전성을 증명할 수 없어서 변조 가능
- 완전성은 정보의 정확성을 말한다. 이것을 증명할 수 없다는 것은 `정보가 정확한지 아닌지 확인할 수 없음`을 의미함.
- 발신된 리퀘스트 혹은 리스폰스와, 수신한 리퀘스트나 리스폰스가 같은지 아닌지 확인할 수 없다. (즉, 중간에 변조가 되어도 이 사실을 알 수 가 없다는 뜻)
- 공격자가 도중에 리퀘스트나 리스폰스를 빼앗아 변조하는 공격을 **Man-in-the-Middle(중간자)** 공격이라고 함.

변조를 방지하기 위해, 자주 사용되는 방법에는 MD5나 SHA-1 등의 해시 값을 확인 / 파일의 디지털 서명 확인 방법이 있다. 그러나 이것만으로 확실히 확인할 수 없어서 `HTTPS`를 사용할 필요가 있다. HTTP 만으로는 완전성을 보증하기 어렵다.

### HTTP + 암호화 + 인증 + 완전성 보호 = HTTPS
- https를 사용하는 통신은 http:// 대신 https:// 를 사용한다.
- https는 SSL의 껍질을 덮어 쓴 HTTP이다. HTTP 통신을 하는 소켓 부분을 SSL이나 TLS라는 프로토콜로 대체한 형태이다.
<img width="318" alt="화면 캡처 2022-10-22 000919" src="https://user-images.githubusercontent.com/45116772/197228757-276c253e-2cd0-4374-80d5-3a622595e3d6.png">
- HTTP는 SSL과 통신, SSL이 TCP와 통신하는 구조

### 상호간 키를 교환하는 공개키 암호화 방식
- SSL은 공개키 암호화 방식을 채용하고 있음
- `공통키 암호화` : 암호화 및 복호화에 하나의 키를 같이 사용하는 방식의 암호화를 말한다. 상대방에게 어떻게 안전하게 키를 배송할 수 있을지 고민하는 문제가 있다.
- 위 문제를 해결하기 위해 **두 개의 키를 사용하는** `공개키 암호화` 방식이 나왔다. 공개키 암호는 서로 다른 두 개의 키 페어를 사용하고, 한 쪽은 **공개키**, 다른 한 쪽은 **비밀키** 라고 부른다.
  - 공개키 암호를 사용한 암호화는 암호를 보내는 측이 **상대의 공개키**를 사용해 암호화를 한다.
  - 암호화된 정보를 받아들인 상대는 자신의 **비밀키**를 사용해 복호화를 실시한다.
  - 이 방식은 암호를 푸는 비밀키는 통신으로 보낼 필요가 없으므로, 도청에 의해 키를 빼앗길 걱정이 없다.
- HTTPS는 공통키 암호화 공개키 암호 양쪽 성질을 가진 하이브리드 암호 시스템이다.
  - 공개키 암호는 공통키 암호에 비해 처리 속도가 늦다.
  - 따라서, **키를 교환하는 곳**에서는 `공개키 암호`를 사용하고, 그 후 통신에서 **메시지를 교환하는 곳**에서는 `공통키 암호`를 사용한다.
- `공개키 암호화`에서 사용하는 공개키는 과연 진짜인가?
  - 이를 증명하고자 **인증 기관(CA)**과 그 기관이 발행하는 공개키 증명서가 이용된다. (예: 인증 기관 - VeriSign사)
  - 브라우저는 안전을 위해 `사전에 주요 인증 기관의 공개키를 내장한 상태`로 제품을 내놓는다.

### HTTPS 동작 원리
- [참고](https://cf-assets.www.cloudflare.com/slt3lc6tev37/5aYOr5erfyNBq20X5djTco/3c859532c91f25d961b2884bf521c1eb/tls-ssl-handshake.png)

---
[이미지 출처](http://www.ktword.co.kr/test/view/view.php?m_temp1=3132)

**Comment by hhhyunwoo** [comment]
## HTTP 약점

### 평문 통신이라서 도청 가능

- HTTP 를 사용한 리퀘스트나 리스폰스 통신 내용은 암호화 되지 않는다.
- TCP/IP는 도청이 가능한 네트워크임
    - 네트워크 상에서 흐르고 있는 패킷을 수집
- 암호화로 도청을 피할 순 있다.
    1. 통신 암호화
        - SSL, TLS 와 같은 다른 프로토콜을 조합해서 HTTP 통신 내용 암호화
    2. 콘텐츠 암호화
        - 바디 자체를 암호화
        - 그렇게 되면 서버든 클라이언트 든 어디서 복호화하는 작업이 필요함

### 통신 상대를 확인하지 않기 때문에 위장 가능

- 누구나 리퀘스트 가능
    - 리퀘스트를 보낸 곳이 위장한 웹 서버일수도 있음
    - 위장한 클라이언트 일 수도 있음 .
    - 특정 상대만 통신 허가 하고 싶은데 불가능
- → SSL을 사용해서 상대 확인 가능. (증명서)

### 데이터의 정확성을 증명할 수 없기 때문에 변조 가능

- 수신한 내용이 다를 수 있음.
    - 상대가 수신할 때까지의 사이에 변조가 되었다고 하더라도 알 수가 없음.
- → MD5, SHA-1 등의 해시 값을 확인하거나, 파일의 디지털 서명을 확인.

## HTTP + 암호화 + 인증 + 완전성 보호 = HTTPS

- SSL, TLS 프로토콜을 통해서 HTTP 통신을 래핑함.
    - 보통 HTTP는 직접 TCP와 통신하지만, SSL을 사용했을 떄는 HTTP는 SSL과 통신, SSL이 TCP와 통신

## 공개키 암호화 방식

### 공통키 암호화

- 양쪽에서 같은 키를 사용
- → 상대에게 키를 넘겨줄 때 빼앗길 우려가 있음

### 공개키 암호화 (비대칭 암호화)

- private key 와 public key를 사용

![image](https://user-images.githubusercontent.com/37402136/197242861-b68c30c4-ca59-46b7-947e-c8a910483814.png)

## HTTPS는 하이브리드 암호 시스템

- 공개기 암호는 공통키 암호보다 처리가 느리기 때문에 모든 통신에 사용하는 것은 비효율 적임
- →
- 공통키 암호로 사용하는 키를 공개키 암호를 사용해서 전달
- 이후 모든 통신은 공통키 암호 기반으로 진행

## 공개키가 정확한지 어떻게 증명?

- CA 등장
    - 신뢰할 수 있는 기관에서 발급.
    - 신뢰할 수 있는 서버임을 보장.
    - 서버의 공개키를 제공
![image](https://user-images.githubusercontent.com/37402136/197307071-3c45b7fe-3799-4170-a873-692ccd896f16.png)

![image](https://user-images.githubusercontent.com/37402136/197242893-aa1839da-147c-4c28-9e41-ea54830f2b70.png)

- 서버의 운영자가 인증 기관에 공개키를 제출
- → CA는 제출된 공개키에 디지털 서명을 하고 서명이 끝난 공개키를 만듬
- → 공개키 인증서에 서명이 끝난 공개키를 담음
- → 서버는 CA에 의해 작성된 공개키 인증서를 클라이언트에게 보내고 공개키 암호로 통신

### 클라이언트 증명서

- 증명서 입수와 배포가 어려움. 유저가 증명서를 인스톨해야하고, 구입해야함.
- 안전성이 매우 높은 인증 기능 제공 가능, 하지만 특정 용도로만 사용되고 있음.

## HTTPS 통신 구조 순서

- 클라이언트와 서버간의 SSL 통신 시작
    - 서버가 클라이언트에게 Certificate 메시지 송신.
        - 메시지에는 공개키 증명서가 포함되어 있음
    - 서버가 Server Hello Done 송신해서 SSL 네고시에이션 끝
- 클라이언트가 Client Key Exchange 메시지로 응답
- HTTP 통신

## HTTPS 문제점

- 통신 속도가 떨어짐
- CPU, Memory 리소스 다량 소비
- SSL에 필요한 통신이 추가되기 때문에 전체적으로 통신량 증가
- 또한 반드시 암호화 처리를 하고 있어서, 서버나 클라이언트가 암호화나 복호화를 위한 계산을 해야함.

**Comment by jjangsungwon** [comment]
## 7장. 웹을 안전하게 하는 HTTPS

### HTTP 약점
#### 도청 가능
- HTTP를 사용한 리퀘스트나 리스폰스 통신 내용은 HTTP 자신을 암호화하는 기능이 없기 때문에 통신 전체가 암호화 되지 않음
- 따라서, 평문(암호화되지 않은 메시지)으로 HTTP 메시지를 보냄
- TCP/IP 는 통신 내용을 도청하기 쉬운 구조임. 패킷 수집(패킷 캡처, 스니퍼)하는 것만으로도 도청 가능. 

#### 위장 가능
- HTTP를 사용한 리퀘스트나 리스폰스에서는 통신 상대를 확인하지 않는다.
- 따라서, 누구나 리퀘스트, 리스폰스를 요청할 수 있다.
- SSL를 사용하면 상대를 확인할 수 있다. 증명서는 신뢰할 수 있는 기관에 의해 발행되는 것이기 때문에 서버나 클라이언트가 실재하는 사실을 증명한다.

#### 완전성 증명 불가능
- 완전성이란 정보의 정확성을 말한다.
- HTTP는 리퀘스트나 리스폰스가 발신된 후에 상대가 수신할 때까지의 사이에 변조된 내용을 파악할 수 없다.
- HTTP를 사용해서 완전성을 확인하기 위한 방법은 있지만, 확실하면서 편리한 방법은 아직 존재하지 않는다.
- SSL 다이제스트 기능을 사용하면 완전성 증명이 가능하다.
  - `Message Digest`: 메시지의 해시값(다이제스트 값)을 계산하여 데이터와 함께 전송. 중간에 패킷을 변조하더라도 다이제스트 값을 확인하면 데이터의 변조 사실을 확인할 수 있다. 

### 암호화
- 도청으로부터 정보를 지키기 위한 방법이 계속 연구되고 있다.

#### 통신 암호화
- HTTP는 SSL, TLS 와 같은 다른 프로토콜을 조합함으로써 HTTP 통신 내용을 암호화할 수 있다.
- SSL 등을 이용해 안전한 통신로를 확립하고 나서 그 통신로를 사용해 HTTP 통신을 수행한다.
- SSL을 조합한 HTTP를 HTTPS(HTTP Secure)나 HTTP over SSL 이라고 한다.

#### 콘텐츠 암호화
- 콘텐츠 내용 자체를 암호화하는 방법이다.
- HTTP에 암호화하는 기능이 없기 때문에 HTTP를 사용해서 운반하는 내용을 암호화화는 방법이다.
- 콘텐츠 암호화를 유용하게 사용하기 위해서는 클라이언트와 서버가 콘텐츠의 암호화나 복호화 구조를 가지고 있어야 한다.

### HTTPS = HTTP + 암호화 + 인증 + 완전성 보호
- HTTPS는 새로운 애플리케이션 계층의 프로토콜이 아니다. HTTP 통신을 하는 소켓 부분을 SSL이나 TLS 프로토콜로 대체하는 것이다.
- 보통 HTTP는 직접 TCP와 통신함. 하지만, SSL을 사용하면 HTTP - SSL - TCP 구조로 통신함

### 공통키 암호화
- 암호화와 복호화에 하나의 키를 같이 사용
- 공통키 암호화 방식을 사용하려면 상대방에게 키를 넘겨줘야함. 하지만, 키를 넘겨주는 과정에서 도청될 수 있음

### 공개키 암호화
- 공통키 암호화 방식의 단점을 해결하기 위해서 나옴
- 서로 다른 두 개의 키 페어(쌍)을 사용함
  - 비밀키: 누구에게도 알려지면 안되는 키
  - 공개키: 누구에게나 알려져도 괜찮은 키
- 암호를 푸는 비밀키를 통신으로 보낼 필요가 없기 때문에 도청에 의해서 키를 빼앗길 걱정이 없음
- 공개키 검증은 CA를 활용하면 됨

### HTTPS는 하이브리드 암호 시스템
- 공통키는 공개키보다 빠름
- 공개키는 도청 걱정이 없음
- HTTPS는 두개의 장점을 적절하게 혼합한 하이브리드 암호 시스템을 사용함
  - 공통키를 사용하기 위한 키 교환에 공개키를 사용. 그 후의 통신은 공통키 암호 사용
- 통신 구조는 책 참고 🙃

### SSL은 느리다?
- CPU나 메모리 등의 리소스를 다량으로 소비함으로써 처리가 느려짐 (암호화, 복호화, 추가적인 통신 ...)
- HTTP에 비해 2~100배 정도 림
- 느려지는 것에 대한 근본적인 해결 방법은 없다 -> 추후에 생기면 SSL도 역사속으로,,
- 현재 SSL 엑셀레이터라는 하드웨어를 사용해서 속도를 해결하고 있음 (SSL 처리하기 위한 전용 하드웨어)

+) HTTPS 를 사용하면 검색엔진 최적화에서 큰 혜택을 볼 수 있음. 구글에서는 HTTPS를 사용하는 웹사이트에 대해서 검색 순위 가산점을 주겠다고 발표했음
