### ISSUE TITLE
8장. 누가 엑세스하고 있는지를 확인하는 인증

### ISSUE THREAD

**Issue by hhhyunwoo** [WhiteKow/http-network-basic-study#8]

**Comment by hhhyunwoo** [comment]
## HTTP 에서 사용하는 인증 방법

- 인증에 대해서 잘 몰랐는데, 한번 짚고갈 수 있어서 좋았음

## BASIC

- 인증이 안되었을 경우 서버에서 401과 함께 www-Authenticate 헤더에 인증 방식을 넣어보냄
- 암호화가 아닌 Base64인코딩으로 패스워드 아이디를 넘겨주기 때문에 위험함
- 잘 안씀

## DIGEST

- 최초에 서버로부터 챌린지 코드를 클라이언트가 받고 리스폰스 코드를 계산해서 보내줌
- 서버는 www-Authenticate 헤더 필드에 nonce와 realm을 보내줌
- BASIC보다는 안전하지만, HTTPS에 비해서 낮다.
- 도청을 방지하기 위한 보호기능은 제공하지만, 위장 방지는 제공 안함
    - id와 패스워드 다 알면 가능하다는 의미

## SSL 클라이언트 인증

- 증명서 사용
- 서버가 클라이언트에게 Certificate Request 메시지 송신
- 보안적으로 매우 우수하지만 유지 비용이 많이 듬

## 폼 베이스 인증

- 잘 이해가 안됨
- 클라이언트가 서버 상의 웹 애플리케이션에 자격 정보를 송신해서 그 자격 정보의 검증 결과에 따라 인증을 하는 방식
- 인증의 대부분은 폼 베이스 인증을 사용함
- 쿠키를 사용해서 세션을 관리함

**Comment by ChanhuiSeok** [comment]
### 8장
HTTP/1.1에서 이용 가능한 인증 방식에 대해 설명하고 있었다.

- **BASIC 인증** : 클라이언트가 id, pw를 Base64 형식으로 인코딩해서 Authorization 헤더 필드에 포함하여 리퀘스트한다. 이것은 전혀 암호화가 되어 있지 않고, 보안상 문제가 있다.

- **DIGEST 인증** : BASIC 인증의 약점을 보완했다. `챌린지 리스폰스` 방식이 추가되어 id, pw를 그대로 보내지는 않는다.
  - `챌린지 리스폰스` : 최초에 상대방에게 인증 요구 보냄 -> 상대방에게 챌린지 코드 받음 -> 이 값으로 리스폰스 코드 계산 -> 그 값을 상대에게 전송하여 인증
  - BASIC 인증보단 보안등급이 높아도, HTTPS 클라이언트 인증보다는 낮다.
  - 패스워드 도청 방지 위한 보호는 제공하나, 위장 방지 기능은 없다. 그래서 그닥 사용하지 않는다.

- **SSL 클라이언트 인증** : id, pw가 도난되었을 때 누군가 위장하는 것을 방지하기 위해 사용한다.
  - HTTPS의 클라이언트 인증서를 이용한 인증 방식
  - 서버가 클라에게 Certificate Request 송신 -> 유저는 송신할 클라이언트 증명서 선택 필요(송신) -> 서버가 클라의 증명서 검증하고 정확하면 클라의 공개키 취득 -> HTTPS에 의한 암호 개시
  - 주로 이것 단독으로만 사용하진 않고 폼 베이스 인증과 합쳐서 2-factor 인증 중 하나로 사용된다.
  - 첫 번째 인증으로 SSL 클라이언트 인증 + 두 번째 인증으로 패스워드로 유저 본인 확인

- **폼 베이스 인증** : 클라가 서버 상의 웹 애플리케이션에 자격 정보를 송신해서 그것의 검증 결과에 따라 인증하는 방식. HTTP 프로토콜로서 사양이 정의된 방식은 아니다.
  - HTTP가 표준으로 제공하는 BASIC, DIGEST 인증은 사용상 문제, 보안 문제로 거의 사용 안한다.
  - SSL 클라이언트 인증도 도입 및 운용 비용 문제로 널리 사용되지 못한다.
  - 웹 사이트 인증 기능 레벨을 충족시킨 표준이 없어서, 웹앱이 제각각 구현하는 폼 베이스 인증을 채용하고 있다.
  - 그래서 표준적인 사양이 있는 것은 아니다.
  - 세션 관리를 위해 쿠키를 활용하는 방법을 자주 사용한다.

**Comment by jjangsungwon** [comment]
## 8장. 인증
- `HTTP/1.1` 에서 이용할 수 있는 인증 방식을 알게 되었다.
- 이를 통해 인증에 대한 개념을 넓힐 수 있었다.

HTTP 에서 사용하는 인증 방법 중 4가지를 다룬다. (BASIC, DIGEST, SSL, 클라이언트 폼 베이스) 이 밖에도 통합 Windows 인증(Kerberos 인증, NTLM 인증) 등이 있다.

### BASIC 인증
- HTTP/1.0에 구현된 인증 방식
- 유저 ID와 패스워드를 콜론(:)으로 연결한 문장을 Base64 형식으로 인코딩하여 전송
- Base64 인코딩은 암호화가 아니기 때문에 부가 정보 없이 복호화 가능 -> 보안상 위험
- 한 번 BASIC 인증을 하면 일반 브라우저에서는 로그아웃할 수 없다.
- 웹 사이트에서 요구되는 보안 등급에 미치지 못한다는 면에서 사용성이 적다.

### DIGEST 인증
- BASIC 인증의 약점을 보안하며 HTTP/1.1에 소개
- 챌린지 리스폰스 방식 사용 -> BASIC 인증과 달리 패스워드를 있는 그대로 보내지 않음
- 패스워드와 챌린지 코드를 이용해서 계산한 결과를 상대에게 보냄
- 패스워드 도청 방지를 위한 보호 기능 제공, 위장 방지하는 기능은 제공 x
- _**DIGEST 인증은 일반 브라우저에서 로그아웃이 가능한가?**_
- BAISC 인증보다는 보안 등급이 높지만 그래도 웹 사이트에서 요구되는 보안 등급에는 미치지 못함

### SSL 클라이언트 인증
- HTTPS의 클라이언트 인증서를 이용한 인증 방식
- 유저 ID, 패스워드가 도난되었더라도 위장을 막을 수 있다
- 서버는 클라이언트 증명서를 검증한 후 클라이언트의 공개키 취득. 그 이후에 HTTPS에 의한 암호 개시
- 2-factor 인증에 사용 (ex, SSL 클라이언트 인증을 사용하여 클라이언트 컴퓨터 인증, 패스워드를 사용하여 유저의 본인 확인)
- 클라이언트 증명서를 이용하기 위해서는 비용이 필요하다는 단점이 존재

### 폼 베이스 인증
- HTTP 프로토콜로서 사양이 정의되어 있는 인증 방식은 아니다.
- 폼 베이스 인증은 표준적인 사양이 결정되어 있지 않지만 일반적으로 세션 관리를 위해서 쿠키를 사용하는 방법을 사용함

_**Q. BASIC 인증을 제외한 인증 방법은 로그아웃이 가능한가?**_
- 쿠키, 세션을 활용한 폼 베이스 인증은 로그아웃이 가능하다고 생각한다. 하지만, DIGEST, SSL 방법은 어떤 방식으로 로그아웃을 하는 것인지 궁금하다.
