### ISSUE TITLE
9장. HTTP에 기능을 추가한 프로토콜

### ISSUE THREAD

**Issue by hhhyunwoo** [WhiteKow/http-network-basic-study#9]

**Comment by hhhyunwoo** [comment]
HTTP 는 매우 중요해졌지만 해당 프로토콜의 근본적인 문제가 있음. 

이를 해결하기 위해서 많은 시도들이 있었음

## HTTP의 병목 현상을 해소하는 SPDY

- 구글이 HTTP의 병목 현상을 해소하고 웹 페이지 로딩 시간을 50% 단축한다는 목표를 세우고 개발 중

### HTTP1.1의 근본적인 문제

- 1개의 커넥션으로 1개의 리퀘스트만 가능
- 리퀘스트는 클라이언트에서만 시작 가능. 리스폰스만 받는 것 불가능
- 헤더 압축 안함
- 장황한 헤더. 중복됨
- 압축 필수 아님

### Ajax

![image](https://user-images.githubusercontent.com/37402136/198682393-f5433d57-8869-4c85-a99d-be432e87bb89.png)

- ajax를 쓰면 유저는 새로운 html을 받는것이 아님.
- javascript가 사용자의 이벤트로부터 DOM을 읽고 XMLHttpRequest 객체 전송을 함
- 이를 통해서 웹 페이지의 일부분만 고쳐쓸 수 있음
- 비동기 통신 방법
- 하지만 HTTP 프로토콜 근본적인 문제 해결은 못함

### Comet

- 클라이언트부터 리퀘스트를 기다리지 않고 클라이언트에 보내기 위한 방법
- 커넥션 유지 시간이 길어짐
- 이 또한 프로토콜 문제 해결 못함

### SPDY

- 프로토콜 수정
- SSL을 필수로 넣음
- SSL과 HTTP 사이에 SPDY 세션 계층을 추가함
- →
    - 다중화 스트림 가능
    - 리퀘스트의 우선 순위부여 가능
    - HTTP 헤더 압축 가능
    - 서버 푸시 가능
    - 서버 힌트 가능
- 병목을 해결하긴 하지만, 한개의 도메인일 경우 통신을 다중화하고, 복수의 도메인은 효과가 한정적이다.

## 브라우저에서 양방향 통신을 하는 WebSocket

- 새로운 프로토콜
- 양방향 통신 규격
- 주로 Ajax나 Comet에서 사용하는 XMLHttpRequest의 결점을 해결하기 위한 기술

### 서버 푸쉬 기능

### 통신량의 삭감

### 프로토콜

- 먼저 HTTP로 서버와 클라이언트가 접속을 함
    - 핸드쉐이크/리퀘스트
        - Upgrade 헤더
    - 핸드쉐이크/리스폰스
        - 101 코드 리턴
- 핸드쉐이크에 의해 커넥션이 확립된 후에는 HTTP가 아닌 Websocket 데이터 프레임을 이용해 통신함
- 

![image](https://user-images.githubusercontent.com/37402136/198682327-fea0a912-570e-450c-9ada-d73c3316fed4.png)
![image](https://user-images.githubusercontent.com/37402136/198682353-82a7ca50-3030-4751-b945-deafcdf932b6.png)
## 등장이 기다려지는 HTTP2.0

- 사용자가 웹을 이용할 떄의 체감 속도의 개선을 목표로 하고 있음

## 웹 서버 상의 파일을 관리하는 WebDAV

- 웹 서버의 콘텐츠에 대해서 직접 파일 복사나 편집 작업 등을 할 수 있는 분산 파일 시스템
- PUT, DELETE 는 보안상 위험해서 안씀
- HTTP1.1 을 확장한 개념임
- WebDAV 만의 추가 메소드와 상태코드가 있음

**Comment by ChanhuiSeok** [comment]
### 9장

HTTP를 기반으로 추가하는 형태로 새로운 프로토콜 몇 가지가 구현되었다.

- **SPDY** : HTTP의 병목 현상 해소 및 웹 페이지 로딩 시간 50% 단축 목표로 개발됨
  - HTTP는 서버 정보 갱신 여부를 알기 위해 항상 확인해야 하고, 서버 정보가 갱신되지 않은 경우는 불필요한 통신이 발생한다.
  - HTTP의 사양 때문에 병목현상이 발생한다.
    - 1개 커넥션은 - 1개 리퀘스트만 가능
    - 리퀘스트는 클라에서만 시작. 리스폰스 받기 불가
    - 리퀘스트, 리스폰스 헤더를 압축하지 않은 채로 보내어 헤더에 정보가 많으면 지연 심함 등
  - HTTP 병목 현상을 해결하기 위해 나온 다른 방식
    - `Ajax` : 비동기 통신 방법 중 하나. 페이지 일부만 갱신해서 리스폰스로 전송되는 데이터 양은 줄어든다. XMLHttpRequest라는 API로 서버와 http 통신 가능. 그러나 실시간으로 서버에서 정보 취득하려고 하면, 대량의 리퀘스트가 발생하는 문제점이 있다.
    - `Comet` : 마치 서버 푸시처럼 동작한다. 서버 측 갱신 발생하면, 클라에서 리퀘스트를 기다리지 않고 보낸다.
    리퀘스트가 오면 리스폰스를 보류하고, 서버가 갱신되었을 때 리스폰스를 반환.
    콘텐츠 실시간 갱신은 가능하나, 리스폰스 보류를 위해 커넥션 유지 시간이 길어진다. 이것도 HTTP 자체 문제를 해결하진 못함.
    - SPDY는 HTTP가 안고 있던 병목 현상을 _프로토콜 레벨_에서 해소하기 위해 개발하고 있다.

- **SPDY**의 설계와 기능
  - TCP/IP 애플리케이션 계층과 트랜스포트 계층 사이에 새로운 세션 계층을 추가하는 형태이다.
  - 보안을 위해 표준으로 SSL을 사용한다.
  - `다중화 스트림`, `리퀘스트 우선순위 부여`, `HTTP 헤더 압축`, `서버 푸시 기능`, `서버 힌트 기능` 등을 HTTP에 추가할 수 있다.
  - SPDY는 기본적으로 한 개의 도메인과 통신만 다중화한다. 하나의 웹 사이트에서 복수의 도메인으로 리소스를 사용한다면 그 효과는 한정적이다.

- **WebSocket** : 웹 브라우저 - 웹 서버를 위한 **양방향 통신 규격**
  - 일단 한 번 서버와 클라가 접속을 맺으면, 그 뒤 통신은 전용 프로토콜로 이루어진다. 한 번 확립 이후에는 서버, 클라이언트 어느 쪽에서도 송신이 가능 (그러므로 서버 푸시도 가능)
  - WebSocket은 한 번 접속 확립 후 유지하려고 하므로 HTTP보다 자주 접속하는 오버헤드도 적어지고, 헤더 사이즈도 작아서 통신량을 줄일 수 있음
  - 한 번 HTTP에 접속을 확립 후, WebSocket에 의해 통신을 하기 위해 핸드쉐이크 절차가 필요하다.
  - 자바스크립트에서는 WebScoekt 인터페이스를 자체적으로 제공하고 있다.

- **HTTP/2.0** : HTTP/1.1은 현재 웹에 적합하다고 볼 수는 없다. 그래서 HTTP/2.0에 대한 표준화를 목표로 진행했다. (https://http2.github.io/)
  - 사용자가 웹을 이용할 때 체감 속도 개선을 목표로 한다. SPDY, HTTP Speed+Mobility + Network-Friendly HTTP Upgrade 가 베이스가 되었다.
  - 2015년에 공식 발표되었다.

- **WebDAV** : 웹 서버 콘텐츠에 대해 직접 파일 복사나 편집을 할 수 있는 분산 파일 시스템이다. HTTP/1.1을 확장한 프로토콜로 RFC에 정의되어 있는 스펙이다.

**Comment by jjangsungwon** [comment]
## 9장. HTTP에 기능을 추가한 프로토콜
- 웹의 용도가 시대를 거치면서 크게 변화하면서 HTTP 프로토콜의 제한, 한계가 드러남
- HTTP의 기능이 부족한 상황에서 전혀 새로운 프로토콜을 만들 수도 있지만, **이미 웹 브라우저라는 환경이 널리 퍼졌기 때문에 HTTP 프로토콜을 무시할 수 없음**. 그래서 HTTP를 기반으로 기능을 추가하는 형태의 프로토콜이 구현됨

### SPDY
- HTTP의 `병목 현상`을 해소하고 웹 페이지 로딩 시간을 50% 단축한다는 목표를 세우고 개발되고 있다.
- 병목 현상의 원인
  - HTTP에서는 서버 정보 갱신을 파악하려면 클라이언트가 서버 측에 확인해야 함
  - 리퀘스트, 리스폰스 헤더를 압축하지 않은 체로 보낸다. 헤더의 정보가 많으면 지연이 심해진다.
  - 데이터 압축을 임의로 선택할 수 있다. 압축해서 보내는 것이 강제적이지는 않다.
- 해결 방법
  - `Ajax` (Asynchronous JavaScript+XML)
    - 웹 페이지 `일부분만` 고쳐쓸 수 있는 비동기 통신 방법
    - XMLHttpRequest API가 핵심 기술. 자바스크립트 등의 스크립트 언어로 서버와 HTTP 통신 가능 -> 이미 읽어 들인 웹 페이지부터 리퀘스트를 발행할 수 있음 -> 페이지의 일부 데이터만 받는 것이 가능함 
    - 하지만, Ajax를 사용해서 실시간으로 서버에서 정보를 취득하려고 하면 대량의 리퀘스트가 발생한다는 문제점이 있음. **여전히 HTTP 프로토콜이 가지고 있는 문제가 해결되지 않음**
  - `Comet`
    - `응답을 연장`시킴으로써, 서버에서 통신을 개시하는 서버 푸시 기능
    - 리스폰스를 보류하기 위해서 커넥션을 유지하는 시간이 길어짐. 커넥션을 유지하는 동안은 리소스를 소비함. **또한 HTTP 자체의 문제는 여전히 해결하지 못함** 
- SPDY의 목표
  - Ajax, Comet 등 사용성을 쾌적하게 하는 여러 가지 기술을 통해 어느정도 속도 개선을 하였지만 HTTP라는 프로토콜의 제약을 없애지는 못함. 근본적인 개선을 위해서는 프로토콜 레벨에서의 개선이 필요함
- SPDY 설계와 기능
  - TCP/IP의 애플리케이션 계층과 트랜스포트 계층 사이에 새로운 세션 계층을 추가하는 형태로 동작
  - 보안을 위해 표준으로 SSL 사용
  - SPDY가 세션 계층으로서 그 사이에 들어감으로써 데이터의 흐름을 제어하지만, HTTP의 커넥션은 확립되어 있다.
  - 다중화 스트림, 리퀘스트 우선 순위 부여, HTTP 헤더 압축, 서버 푸시 기능, 서버 힌트 기능 제공
- 단점
  - `한 개의 도메인(IP 주소)`과의 통신을 다중화할 뿐이기 때문에 하나의 웹 사이트에서 복수의 도메인으로 리소르를 사용하고 있는 경우 효과는 한정적이다.    

### WebSocket
- Ajax와 Comet 을 사용한 통신은 웹 브라우징을 고속화하지만 HTTP 프로토콜을 사용하고 있는 이상, 병목 현상을 해결할 수 없었다. WebSocket은 새로운 프로토콜과 API에 의해 이 문제를 해결한다.
- 웹 서버와 클라이언트가 한 번 접속을 확립하면 그 뒤의 통신을 모두 전용 프로토콜로 하는 방식으로 JSON이나 XML, HTML이나 이미지 등 임의 형식의 데이터를 보내게 된다.
- 한 번 접속을 확립하면 서버와 클라이언트 어느쪽에서도 송신을 할 수 있게 된다.
- 서버 푸시 기능, 통신량의 삭감, 핸드쉐이크/리퀘스트 기능 제공

### HTTP/2.0
- 사용자가 웹을 이용할 때의 체감 속도 개선을 목표로 하고 있다.
- HTTP/1.1 경유로 TCP를 사용하는 것이 기본으로 되어 있기 때문에 SPDY, HTTP Speed+Mobility, Network-Friendly HTTP Upgrade 프로토콜이 베이스가 되어 사양이 검토되었다.

### WebDAV (Web-based Distributed Authoring and Versioning)
- 웹 서버의 콘텐츠에 대해서, 직접 파일 복사나 편집 작업 등을 할 수 있는 분산 파일 시스템이다.
- 파일 작성, 삭제 등 기본적인 기능 이외에 파일 작성자 등의 관리나 편집 중에 다른 유저가 다시 고쳐 쓰지 못하도록 잠금 기능, 갱신 정보를 관리하는 리비전 기능 등이 준비되어 있다.

**_+) 왜 HTTP는 이렇게까지 사용되고 있는가?_**
- 대표적인 이유는 방화벽 설정이다. HTTP는 많은 회사나 조직에서 허가된 통신 환경인 경우가 많기 때문에 방화벽의 설정을 변경할 필요가 없고 HTTP라면 도입이 용이하다는 장점이 있다.
